# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy to the server

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Deploy JAR file to the server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: build/libs/pirtip-server-0.0.1-SNAPSHOT.jar
        target: /home/${{ secrets.USERNAME }}/deploy/${{ github.sha }}
        strip_components: 2
    - name: Create a symbolic link to JAR file
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ln -sfn /home/${{ secrets.USERNAME }}/deploy/${{ github.sha }}/pirtip-server-0.0.1-SNAPSHOT.jar /home/${{ secrets.USERNAME }}/pirtip-server.jar
